[theme]
base="dark"
textColor="#ffffff"
font="sans serif"

# Comment in entries below for light colored theme
#primaryColor="#F63366"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
